on:
  create:
    tags:
      - 'v*'

name: Release version

jobs:
  build:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Release
        run: |
          echo lets do the release.
      - name: Bump version
        run: |
          sed -i "s%version=.*%version=$VERSION%g" gradle.properties
        env:
          VERSION: $(sed -n '1s/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/p' gradle.properties)
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "[skip travis] Bumb version" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: $(sed -n '1s/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/p' gradle.properties)
        with:
          tag_name: v$NEXT_VERSION
          release_name: draft
          draft: true
          prerelease: false
